### ISSUE TITLE
VS2017 C4577 when Packaging

### ISSUE THREAD

**Issue by error454** [getnamo/ZipUtility-Unreal#30]
I'm on latest/greatest ZipUtility and have been having some issues since switching over to VS2017. The problem is occurring both on 4.19 and 4.21 engine builds for me.

Everything works great in the editor and I can zip and unzip all day long. When I go to package, I get C4577:

```
    [14/16] Module.ZipUtility.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\INCLUDE\vcruntime_new.h(71): error C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
```

If I add `bEnableExceptions = true;` to `ZipUtility.Build.cs` then I'm able to finish packaging, however now all zip operations fail immediately (`Extractor.ExtractFilesFromArchive` always returns false). I'm making a custom build of the 7zip-cpp so I can debug further. I'm just wondering why nobody else has encountered C4577, it makes me think something is wrong in my environment.

There's [this popular discussion on C4577](https://answers.unrealengine.com/questions/348151/c4577-noexcept-used-with-no-exception-handling-mod.html) in UE4, which is where I got the idea to enable exceptions outright in the module.

**Comment by Tkappa** [comment]
Hi, I had the same problem and fixed it in the same way but on my end it works correctly.   
I'm using VS2017 and the 4.21 build too.
