### ISSUE TITLE
Visual Studio 2019 doesn't compile

### ISSUE THREAD

**Issue by Eamirus** [getnamo/ZipUtility-Unreal#34]
By default, it searches for vs17 registry edit in build.cs file, and uses "C:\Program Files (x86)\Microsoft Visual Studio\2017" if not found. If there is no 2017 version, the compile fails. fixable by adding another check for VS2019

**Comment by getnamo** [comment]
make a pull request and I'll merge it

**Comment by progammer4538** [comment]
hello

**Comment by getnamo** [comment]
Fixed in https://github.com/getnamo/ZipUtility-Unreal/releases/tag/v1.1.1
