### ISSUE TITLE
'ModuleManager.h': No such file or directory

### ISSUE THREAD

**Issue by saulfm15** [getnamo/ZipUtility-Unreal#36]
I have been trying to install this plugin in 4.25.4, when i open my project works as normal, in bluprints i can ad the ZipUtility nodes, but when I Run the project it crash when it access to the ZipUtility.
I open the .sln project and shows an error while trying access "ZipFileFunctionLibrary.cpp", and when i compile the project,  'ModuleManager.h': No such file or directory, this error shows up, i already try by adding the directions on the codes by this metod:  #include "Modules/ModuleManager.h"
more errors of that type appear and i do the same till the stop to show up, I compile and run in the editor, and again the project crash while accessing the ZipUtility on play

**Comment by Demasoka** [comment]
Hello! I Have the same problem :( Do you know any fix?

**Comment by saulfm15** [comment]
I uninstall, delete, redownload and reinstall the plugin and that make it work, i guess some file was corrupted or something

**Comment by ArosPrince** [comment]
I have exactly the same issue. 4.25.4 crashes when calling the Zip node.

If I try to compile from sources so that I get more info, it would not compile because of the error in the ticket headline.

Not sure how's that supposed to work because if you look into the documentation, it's supposed to be:

`#include "Modules/ModuleManager.h"`

(i.e. with the Modules/ prefix)

See:
https://docs.unrealengine.com/4.26/en-US/API/Runtime/Core/Modules/FModuleManager/

**Comment by getnamo** [comment]
See above or https://github.com/getnamo/socketio-client-ue4/#via-git-clone

**Comment by ArosPrince** [comment]
I do. I have also tried redownloading it (which makes little sense, but still) and setting up a completely new blank project. I tried both v0.10.0 and v0.9.0. Still, running a BP only project would crash and trying to compile a C++ project would not compile because of the error above.

**Comment by getnamo** [comment]
Check path is absolute and confirm file/folder exists

This is 4.25/win64?

**Comment by ArosPrince** [comment]
Hi, sorry for the late response. Somehow I missed the notification.

Yes, it's 4.25.4/win64

**Comment by getnamo** [comment]
Fixed in https://github.com/getnamo/ZipUtility-Unreal/releases/tag/v1.1.1 for VS2019
