### ISSUE TITLE
i cannot compile my project

### ISSUE THREAD

**Issue by PotatoGod937** [getnamo/ZipUtility-Unreal#42]
when i compile my project i get an error
![Ue4ZipUtilityProblem](https://user-images.githubusercontent.com/58158498/118815003-1e9bf380-b8f4-11eb-86cb-1bedeab95baf.PNG)

**Comment by getnamo** [comment]
See https://github.com/getnamo/ZipUtility-ue4#note-on-compiling

**Comment by getnamo** [comment]
Fixed in https://github.com/getnamo/ZipUtility-Unreal/releases/tag/v1.1.1 for VS2019
