### ISSUE TITLE
UE5.2 doesnt compile it

### ISSUE THREAD

**Issue by AlexanderRex** [getnamo/ZipUtility-Unreal#50]
Hello, can you help me plese with transfering your plugin to 5.2 version?

I have this error

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'HideWindowsPlatformTypes.h': No such file or directory	GridExporterDemo	D:\UnrealProjects\GridExporterDemo\Plugins\ZipUtility-Unreal\ThirdParty\7zpp\Include\SevenZipException.h	30

**Comment by AlexanderRex** [comment]
So, it works now, I have fix this lines

#include "Windows/HideWindowsPlatformAtomics.h"
#include "Windows/HideWindowsPlatformTypes.h"
#include "Windows/PostWindowsApi.h"

will check blueprint functionality next

**Comment by AlexanderRex** [comment]
still have problems with that, but ATL is installed

#include "atlbase.h"

**Comment by kira2015** [comment]
“HideWindowsPlatformTypes.h”: No such file or directory	cpp	D:\Epic Games\project\cpp\Plugins\ZipUtility-Unreal\ThirdParty\7zpp\Include\SevenZipException.h	30

**Comment by oivio** [comment]
> “HideWindowsPlatformTypes.h”: No such file or directory cpp D:\Epic Games\project\cpp\Plugins\ZipUtility-Unreal\ThirdParty\7zpp\Include\SevenZipException.h 30

Just change to “Windows/HideWindowsPlatformTypes.h”

**Comment by getnamo** [comment]
Added fixes and published a release: https://github.com/getnamo/ZipUtility-Unreal/releases/tag/v1.2.0
