### ISSUE TITLE
UE5.3 doesnt compile it

### ISSUE THREAD

**Issue by kofein3d** [getnamo/ZipUtility-Unreal#51]
Hello, can you help me plese with transfering your plugin to 5.3 version?

I have  error
  SevenZipException.h(30): [C1083] Cannot open include file: 'HideWindowsPlatformTypes.h': No such file or directory

**Comment by getnamo** [comment]
5.3 released: https://github.com/getnamo/ZipUtility-Unreal/releases/tag/v1.3.0
